chicagodir/streets/forms.py
# -*- coding: utf-8 -*-
"""Street forms."""
import datetime

from flask_wtf import FlaskForm
from wtforms import (
    BooleanField,
    DateField,
    Field,
    FieldList,
    Form,
    FormField,
    IntegerField,
    SelectField,
    StringField,
    TextAreaField,
)
from wtforms.validators import DataRequired, Length, NumberRange, Optional
from wtforms.widgets import TextInput

direction_choices = [("", ""), ("N", "N"), ("S", "S"), ("E", "E"), ("W", "W")]


def int_or_none(x) -> int:
    """Either convert x to an int or return None."""
    try:
        return int(x)
    except TypeError:
        return None
    except ValueError:
        return None


class TagListField(Field):
    """A List of string tags."""

    widget = TextInput()

    def _value(self):
        """Process the data."""
        if self.data:
            return ", ".join(self.data)
        else:
            return ""

    def process_formdata(self, valuelist):
        """Process form data."""
        if valuelist:
            self.data = list({x.strip() for x in valuelist[0].split(",") if x.strip()})
        else:
            self.data = []


year_choices = [(None, "")] + [
    (i, str(i)) for i in reversed(range(1833, datetime.date.today().year + 1))
]


class StreetSearchForm(Form):
    """The form for searching for a street."""

    name = StringField("Name", validators=[Optional(), Length(max=40)])
    year = SelectField(
        "Year",
        coerce=int_or_none,
        validators=[Optional()],
        choices=year_choices
        # list(reversed(range(1833, datetime.date.today().year + 1))),
        # default=datetime.date.today().year,
    )
    confirmed = BooleanField("Confirmed")
    term = StringField("Query", validators=[Optional(), Length(max=40)])


class ChangeForm(Form):
    """The subform for modifying a successor/predecessor change."""

    date = DateField("Date of Change", validators=[Optional()])
    note = StringField("Note", validators=[Optional()])
    remove = BooleanField("Current", default=False)
    to_id = SelectField(
        "Street",
        coerce=int,
    )
    # from_id = SelectField("Street", coerce=int)


class StreetEditForm(FlaskForm):
    """Register form."""

    direction = SelectField("Direction", choices=direction_choices)
    name = StringField("Name", validators=[DataRequired(), Length(max=40)])
    suffix = StringField("Suffix", validators=[Length(max=8)])

    grid_direction = SelectField("Grid Direction", choices=direction_choices)

    grid_location = IntegerField(
        "Grid Location", validators=[Optional(), NumberRange(min=0, max=150000)]
    )
    diagonal = BooleanField("Diagonal")
    max_address = IntegerField(
        "Max Address", validators=[Optional(), NumberRange(min=0, max=1500000)]
    )
    min_address = IntegerField(
        "Min Address", validators=[Optional(), NumberRange(min=0, max=150000)]
    )

    suffix_direction = SelectField("Suffix Direction", choices=direction_choices)

    start_date = DateField("Start Date", validators=[Optional()])
    start_date_circa = BooleanField("circa")

    end_date = DateField("End Date", validators=[Optional()])
    end_date_circa = BooleanField("circa")

    current = BooleanField("Current")
    vacated = BooleanField("Vacated")

    historical_note = TextAreaField("Historical Note")
    text = TextAreaField("Source Notes")
    successors = FieldList(FormField(ChangeForm))
    confirmed = BooleanField("Confirmed")
    weird = BooleanField("Weird")
    skip = BooleanField("Skip")

    tags = TagListField("Tags")

    new_successor_street_date = DateField("Date of Change", validators=[Optional()])
    new_successor_street_note = StringField("Note", validators=[Optional()])

    new_successor_street = SelectField(
        "Street",
        coerce=int_or_none,
    )

    def set_street_choices(self, street_choices):
        """Set up for proper street choices."""
        for successor in self.successors:
            successor.to_id.choices = street_choices

        self.new_successor_street.choices = [(None, "")] + street_choices

chicagodir/streets/__init__.py
# -*- coding: utf-8 -*-
"""The directory module."""
from . import views  # noqa

chicagodir/streets/views.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
import datetime
import io

import markdown
import redis
from flask import (
    Blueprint,
    abort,
    current_app,
    jsonify,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from rq import Connection, Queue
from sqlalchemy.orm.exc import MultipleResultsFound, NoResultFound

from chicagodir.database import db
from chicagodir.directory.forms import StreetListForm
from chicagodir.streets.models import Street, StreetChange
from chicagodir.streets.sorting import streets_sorted
from chicagodir.streets.streetlist import StreetList, StreetListEntry

from .forms import StreetEditForm, StreetSearchForm
from .tasks import (
    calc_successor_info,
    inherit_grid,
    redraw_affected_tags,
    redraw_map_for_street,
    redraw_map_for_streetlist,
    refresh_community_area_tags,
)

blueprint = Blueprint("street", __name__, static_folder="../static")

# lifted from sqlalchemy_utils
# \ is the escape character postgres defaults to
def escape_like(string, escape_char="\\"):
    """
    Escape the string paremeter used in SQL LIKE expressions.

    ::

        from sqlalchemy_utils import escape_like


        query = session.query(User).filter(
            User.name.ilike(escape_like('John'))
        )


    :param string: a string to escape
    :param escape_char: escape character
    """
    return (
        string.replace(escape_char, escape_char * 2)
        .replace("%", escape_char + "%")
        .replace("_", escape_char + "_")
    )


@blueprint.route("/streets", methods=["GET"])
def street_search():
    """Search database for streets."""
    form = StreetSearchForm(request.args)
    if request.query_string and form.validate():
        q = db.session.query(Street)
        if form.year.data:

            year = form.year.data
            first_of_year = datetime.date(month=1, day=1, year=year)
            q = q.filter(
                ((Street.start_date < first_of_year) | (Street.start_date.is_(None)))
                & ((Street.end_date > first_of_year) | (Street.end_date.is_(None)))
            )
        if form.term.data:
            q = q.filter(
                (Street.name.ilike("%" + escape_like(form.term.data) + "%"))
                | (Street.street_id.ilike(escape_like(form.term.data) + "%"))
            )

        results = streets_sorted(q.limit(15).all())
        return jsonify(
            [
                {
                    "name": street.full_name,
                    "id": street.id,
                    "info": street.short_tag(),
                    "label": street.context_info,
                }
                for street in results
            ]
        )


@blueprint.route("/street/", methods=["GET", "POST"])
def street_listing():
    """Show all the known streets."""
    form = StreetSearchForm(request.args)
    year_str = "as of today"
    if request.query_string and form.validate():
        q = db.session.query(Street)
        if form.year.data:

            year = form.year.data
            first_of_year = datetime.date(month=1, day=1, year=year)
            q = q.filter(
                ((Street.start_date < first_of_year) | (Street.start_date.is_(None)))
                & ((Street.end_date > first_of_year) | (Street.end_date.is_(None)))
            )
            year_str = "as of {}".format(str(year))

        if form.name.data:
            q = q.filter(Street.name.ilike("%" + escape_like(form.name.data) + "%"))

        if form.confirmed.data is not None:

            q = q.filter(Street.confirmed == form.confirmed.data)

        # end filters
        current_streets = streets_sorted(q.all())
        current_app.logger.info(form.confirmed.data)

    else:
        current_streets = streets_sorted(
            db.session.query(Street).filter(Street.current.is_(True)).all()
        )
    total_count = len(current_streets)
    street_groups = []
    for i in range(0, len(current_streets), 100):
        street_groups.append(current_streets[i : i + 100])
    # street_groups = itertools.zip_longest(current_streets * 100)
    return render_template(
        "streets/street_listing.html",
        current_streets=street_groups,
        # withdrawn_streets=Street.query.filter_by(current=False).all(),
        search_form=form,
        year_str=year_str,
        total_count=total_count,
    )


@blueprint.route(
    "/street/missing_start/",
    methods=[
        "GET",
    ],
)
def missing_start():
    """Show all the known streets."""
    form = StreetSearchForm(request.args)
    current_streets = streets_sorted(
        db.session.query(Street).filter(Street.start_date.is_(None)).all()
    )
    total_count = len(current_streets)

    street_groups = []
    for i in range(0, len(current_streets), 100):
        street_groups.append(current_streets[i : i + 100])
    # street_groups = itertools.zip_longest(current_streets * 100)
    return render_template(
        "streets/street_listing.html",
        current_streets=street_groups,
        search_form=form,
        year_str="missing start year",
        total_count=total_count,
    )


@blueprint.route(
    "/street/missing_end/",
    methods=[
        "GET",
    ],
)
def missing_end():
    """Show all the known streets that are not current but have no end date."""
    form = StreetSearchForm(request.args)
    current_streets = streets_sorted(
        db.session.query(Street)
        .filter((Street.end_date.is_(None)) & (Street.current.is_not(True)))
        .all()
    )
    total_count = len(current_streets)

    street_groups = []
    for i in range(0, len(current_streets), 100):
        street_groups.append(current_streets[i : i + 100])
    # street_groups = itertools.zip_longest(current_streets * 100)
    return render_template(
        "streets/street_listing.html",
        current_streets=street_groups,
        search_form=form,
        year_str="missing retirement year",
        total_count=total_count,
    )


@blueprint.route("/street/<string:tag>/", methods=["GET", "POST"])
def view_street(tag: str):
    """Let's look at a historical street."""
    try:
        d = Street.query.filter_by(street_id=tag).one()
    except NoResultFound:
        abort(404)
    except MultipleResultsFound:
        abort(500)
    return render_template(
        "streets/street_index.html",
        street=d,
        source_notes=markdown.markdown(d.text.replace("\t", "")),
    )


def remove_successor(street, change_to_remove):
    """Remove an association to a successor street."""
    street.record_edit(
        current_user,
        "removed sucessor {} ({})".format(
            change_to_remove.to_street.full_name, change_to_remove.to_street.street_id
        ),
    )
    change_to_remove.to_street.record_edit(
        current_user,
        "removed predecessor {} ({})".format(street.full_name, street.street_id),
    )
    change_to_remove.delete()


def add_successor(street, new_successor):
    """Record the addition of a new successor."""
    street.record_edit(
        current_user,
        "added successor {} ({})".format(
            new_successor.to_street.full_name, new_successor.to_street.street_id
        ),
    )
    new_successor.to_street.record_edit(
        current_user,
        "added predecessor {} ({})".format(street.full_name, street.street_id),
    )


@blueprint.route("/street/<string:tag>/edit", methods=["GET", "POST"])
@login_required
def edit_street(tag: str):
    """Editing a street."""
    try:
        d = Street.query.filter_by(street_id=tag).one()
    except NoResultFound:
        abort(404)
    except MultipleResultsFound:
        abort(500)

    # WTForms is weird when the method is GET
    if request.method != "GET":
        form = StreetEditForm(request.form, obj=d)
    else:
        form = StreetEditForm(None, obj=d)

    # set up street choices
    street_choices = [
        (street.id, street.full_name)
        for street in streets_sorted(d.contemporary_streets())
    ]
    form.set_street_choices(street_choices)

    if form.validate_on_submit():
        form.populate_obj(d)

        # remove successor streets marked for deletion
        for to_remove in [x for x in d.successors if x.remove]:
            remove_successor(d, to_remove)

        #  check for new successor street
        if form.new_successor_street.data is not None:
            new_successor = StreetChange(
                from_id=d.id,
                to_id=form.new_successor_street.data,
                date=form.new_successor_street_date.data,
                note=form.new_successor_street_note.data,
            )
            new_successor.save()
            add_successor(d, new_successor)

        d.record_changes(current_user)

        d.save()

        with Connection(redis.from_url(current_app.config["REDIS_URL"])):
            q = Queue()
            q.enqueue(refresh_community_area_tags, d.street_id)
            q.enqueue(redraw_map_for_street, d.street_id)
            q.enqueue(calc_successor_info, d.street_id)
            q.enqueue(inherit_grid, d.street_id)
            q.enqueue(redraw_affected_tags, d.street_id)

        return redirect(url_for("street.view_street", tag=tag))
    elif form.is_submitted():
        current_app.logger.warning("submitted but invalid")
    return render_template("streets/street_edit.html", street=d, street_form=form)


@blueprint.route("/streets/list/<int:streetlist_id>/", methods=["GET", "POST"])
def view_streetlist(streetlist_id: int):
    """Viewing a streetlist."""
    try:
        sl = StreetList.query.filter_by(id=streetlist_id).one()
    except NoResultFound:
        abort(404)
    except MultipleResultsFound:
        abort(500)

    return render_template(
        "streets/streetlist_view.html",
        streetlist=sl,
    )


@blueprint.route("/streets/list/new", methods=["GET", "POST"])
@login_required
def new_streetlist():

chicagodir/templates/streets/street_index.html
{% extends "layout.html" %}

{% block css %}
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="{{street.full_name}} – {{street.retirement_info()}}">
<meta name="twitter:description" content="{{street.historical_note}}">
<meta name="twitter:image"
    content="https://chicitydir.us-east-1.linodeobjects.com/streets/maps/{{street.street_id}}.png">
{% endblock %}

{% block page_title %}
chicagocity.directory / {{street.full_name}}
{% endblock %}

{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->


<div class="container">

    {% if street.current %}

    <h3>Current Street</h3>
    <h1 class="display-4">{{street.full_name}} </h1>

    {% else %}
    <h3>{{street.retirement_info() }}</h3>
    <h1 class="display-4">
        {{street.full_name}} </h1>

    {% endif %}
    <h4>{{street.grid_location}}{{street.grid_direction}} | from
        {{street.min_address|default("___", true)}}
        to
        {{street.max_address|default("___", true)}}
    </h4>
    {% if street.start_date or street.end_date or street.current %}
    {% if street.current %}
    <h4>{{street.start_date_info()|default("?", true)}} - present</h4>

    {% else %}
    <h4>{{street.start_date_info()|default("?", true)}} – {{street.end_date_info()}}</h4>
    {% endif %}

    {% endif %}
    {% for annex in street.annexations() %}
    <h5>Possibly part of the {{annex.name}} annexation in {{annex.year}}.</h5>
    {% endfor %}
    <div>{{street.historical_note}}</div>

    <div class="container px-4 py-5" id="icon-grid">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-5">

            {% if street.tags %}
            <div class="card d-flex align-items-start">

                <div class="card-body">
                    <h4 class="card-title fw-bold mb-0">Tags</h4>
                    <ul class="list-group list-group-flush">
                        {% for tag in street.tags %}
                        <li class="list-group-item"><i class="fas fa-tag"></i><a
                                href="{{ url_for('street.view_tag', tag=tag) }}">{{tag}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endif %}
            <div class="card d-flex align-items-start">
                <div class="card-body">
                    <h4 class="card-title fw-bold mb-0"> <i class="fas fa-map-marked"></i>
                        Location</h4>
                    <img width="250px"
                        src="https://chicitydir.us-east-1.linodeobjects.com/streets/maps/{{street.street_id}}.png">
                </div>
            </div>
            {% if street.predecessor_changes().count() %}
            <div class="card d-flex align-items-start">

                <div class="card-body">
                    <h4 class="card-title fw-bold mb-0"><i class="fas fa-arrow-alt-circle-left"></i> Predecessors</h4>
                    <ul class="list-group list-group-flush">
                        {% for page in street.predecessor_changes() %}
                        <li class="list-group-item"><a
                                href="{{ url_for('street.view_street', tag=page.from_street.street_id) }}">{{page.from_street.full_name}}</a>
                            {{page.from_street.short_tag()}}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endif %}
            {% if street.successor_changes().count() %}
            <div class="card  d-flex align-items-start">

                <div class="card-body">
                    <h4 class="card-title fw-bold mb-0"><i class="fas fa-arrow-alt-circle-right"></i> Successors</h4>
                    <ul class="list-group list-group-flush">
                        {% for page in street.successor_changes() %}
                        <li class="list-group-item"><a
                                href="{{ url_for('street.view_street', tag=page.to_street.street_id) }}">{{page.to_street.full_name}}</a>
                            {{page.to_street.short_tag()}}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endif %}
            {% if street.street_lists() %}
            <div class="card  d-flex align-items-start">

                <div class="card-body">
                    <h4 class="card-title fw-bold mb-0"><i class="fas fa-list"></i>Appears in
                    </h4>
                    <ul class="list-group list-group-flush">
                        {% for list in street.street_lists() %}
                        <li class="list-group-item"><a
                                href="{{url_for('street.view_streetlist', streetlist_id=list.id)}}">
                                {{list.name}} ({{list.date.year}})</a>

                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endif %}
            {% if street.stored_maps() %}

            <div class="card  d-flex align-items-start">

                <div class="card-body">
                    <h4 class="card-title fw-bold mb-0"><i class="fas fa-atlas"></i>Might appear within
                    </h4>
                    <ul class="list-group list-group-flush">
                        {% for map in street.stored_maps() %}
                        <li class="list-group-item"><a target="_blank" href="{{map.url}}"> {{map.name}}</a>

                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endif %}
            {% if street.data_issues() %}
            <div class="card d-flex align-items-start">

                <div class="card-body">
                    <h4 class="card-title fw-bold mb-0"><i class="fas fa-clipboard-check"></i> Data Issues</h4>
                    <ul class="list-group list-group-flush"> {% for issue in street.data_issues() %}
                        <li class="list-group-item list-group-item-{{issue.level}}"><i class="{{issue.icon}}"></i>
                            {{issue.issue}}</li> {% endfor %}
                    </ul>
                    {% if current_user and current_user.is_authenticated %}
                    <a class="btn btn-primary" href="edit">edit</a>
                    {% else %}
                    <a class="btn btn-primary" href="{{url_for('public.register')}}">create an account to edit</a>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-5">

            {% if street.similar_streets().count() %}
            <div class="card d-flex align-items-start">

                <div class="card-body">
                    <h4 class="card-title fw-bold mb-0"> <i class="fas fa-eye"></i> Similarly named streets</h4>
                    <ul class="list-group list-group-flush">
                        {% for similar_street in street.similar_streets() %}
                        <li class="list-group-item"><a
                                href="{{ url_for('street.view_street', tag=similar_street.street_id) }}">{{similar_street.full_name}}</a>
                            {{similar_street.short_tag()}}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endif %}

            {% if street.streets_with_same_grid() %}
            <div class="card d-flex align-items-start">

                <div class="card-body">
                    <h4 class="card-title fw-bold mb-0"> <i class="fas fa-unlink"></i> Aligned Streets</h4>
                    <ul class="list-group list-group-flush">
                        {% for similar_street in street.streets_with_same_grid() %}
                        <li class="list-group-item"><a
                                href="{{ url_for('street.view_street', tag=similar_street.street_id) }}">{{similar_street.full_name}}</a>
                            {{similar_street.short_tag()}}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endif %}
            <div class="card d-flex align-items-start">

                <div class="card-body">
                    <h4 class="card-title fw-bold mb-0"><i class="fas fa-book-reader"></i> Source Notes</h4>
                    <p>{{source_notes|safe}}</p>
                </div>
            </div>
            <div class="card d-flex align-items-start">

                <div class="card-body">
                    <h4 class="card-title fw-bold mb-0"><i class="fas fa-history"></i> Edit History</h4>
                    <ul class="list-group list-group-flush"> {% for edit in street.edits|reverse %}
                        <li class="list-group-item small">{% if edit.timestamp %}
                            {{edit.timestamp.date()}} | <i>{{edit.user.username}}</i> | {{edit.note}}<br>
                            {% else %}
                            import | <i>{{edit.user.username}}</i> | {{edit.note}}<br>

                            {% endif %}</li>
                        {% endfor %}

                    </ul>
                </div>
            </div>


        </div>
    </div>





</div>
{% endblock %}

chicagodir/templates/streets/streetlist_edit.html
{% extends "layout.html" %}


{% macro validated_field(field) -%}
{% if field.errors %}

{{ field(class_="form-control is-invalid") }}
{% for error in field.errors %}
<div class="invalid-feedback">
    {{error}}
</div>
{% endfor %}
{% else %}
{{ field(class_="form-control") }}
{% endif %}

{%- endmacro %}

{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->

<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/street/">Streets</a></li>
            <li class="breadcrumb-item"><a href="/streets/lists/">Lists</a></li>

            <li class="breadcrumb-item" aria-current="page"><a
                    href="{{url_for('street.view_streetlist', streetlist_id=streetlist.id)}}">
                    {{streetlist.name}}
                    ({{streetlist.date.year}})</a></li>
            <li class="breadcrumb-item active">edit</li>

        </ol>
    </nav>
    <h2>{{streetlist.name}} - {{streetlist.year}}</h2>

    <form method="post">
        {{ street_list_form.csrf_token }}
        <h2>Editing {{streetlist.name}}</h2>
        <div class="row">
            <div class="col">
                <h3>Street List Info</h3>
                <table>

                    <tr>
                        <td><label for="name">Name</label></td>
                        <td>
                            {% if street_list_form.name.errors %}

                            {{ street_list_form.name(class_="form-control is-invalid") }}
                            {% for error in street_list_form.name.errors %}
                            <div class="invalid-feedback">
                                {{error}}
                            </div>
                            {% endfor %}
                            {% else %}
                            {{ street_list_form.name(class_="form-control") }}
                            {% endif %}
                        </td>
                    </tr>

                    <tr>
                        <td><label for="date"></label>Date</label></td>

                        <td>
                            {{street_list_form.date(class_="form-control")}}

                        </td>


                    </tr>

                    <tr>
                        <td><label for="url">URL</label>

                        </td>
                        <td class="align-top">
                            {{validated_field(street_list_form.url)}}
                        </td>
                    </tr>
                    <tr>
                        <td><label for="url">Text</label>

                        </td>
                        <td class="align-top">
                            {{validated_field(street_list_form.text)}}
                        </td>
                    </tr>


                </table>

                <h3>Streets</h3>
                <table class="table table-sm">

                    <tbody>
                        {% for subgroup in streetlist.sorted_entries()|batch(4) %}

                        <tr>
                            {% for entry in subgroup %}
                            <td>{{entry.street.full_name}} <i>
                                    {{entry.street.grid_info()}} {{entry.street.short_tag()}}</i>

                                <a class="btn-danger" href="{{url_for('street.remove_street_from_streetlist',
                                    entry_id=entry.id, streetlist_id=streetlist.id)}}">✗</a>
                            </td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                        <tr>
                            <th>add a new entry</th>
                            </tg>
                        </tr>

                        <tr>
                            <td><input class="autocomplete" id="street_search">
                                <input type="hidden" name="new_entry_street" id="street_search-id">
                            </td>

                        </tr>
                    </tbody>
                </table>




                {% if street_list_form.errors %}
                <ul class="errors">
                    {% for error, value in street_list_form.errors.items() %}
                    <li>{{ error }} {{value}}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <input class="btn btn-primary" type="submit" value="submit">
            </div>

        </div>
    </form>





</div>
{% endblock %}

chicagodir/templates/streets/streetlist_list.html
{% extends "layout.html" %}
{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->





<script>
  if (typeof ($.fn.popover) != 'undefined') {
    alert("uh oh");
  }
</script>
<div class="container">

  <header class="py-3 mb-4 border-bottom">
    <div class="container d-flex flex-wrap justify-content-center">
      <a href="/street/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none">
        <i class="fas fa-road"></i>
        <span class="fs-4">Chicago Streets appearing in Historic Resources</span>
      </a>

    </div>
  </header>
  <ul class="list-group list-group-flush">
    {% for list in streetlists %}
    <li class="list-group-item"><a href="{{url_for('street.view_streetlist', streetlist_id=list.id)}}">
        {{list.name}} ({{list.date.year}})</a>

    </li>
    {% endfor %}
  </ul>
</div>

{% endblock %}

chicagodir/templates/streets/tags_list.html
{% extends "layout.html" %}
{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->





<script>
  if (typeof ($.fn.popover) != 'undefined') {
    alert("uh oh");
  }
</script>
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item"><a href="/street/">Streets</a></li>
      <li class="breadcrumb-item active" aria-current="page">Tags</li>

    </ol>
  </nav>
  <header class="py-3 mb-4 border-bottom">
    <div class="container d-flex flex-wrap justify-content-center">
      <a href="/street/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none">
        <i class="fas fa-road"></i>
        <span class="fs-4">All Tags</span>
      </a>

    </div>
  </header>
  <ul class="list-group list-group-flush">
    {% for tag in all_tags %}
    <li class="list-group-item"><a href="{{url_for('street.view_tag', tag=tag)}}">
        {{tag}}</a>

    </li>
    {% endfor %}
  </ul>
</div>

{% endblock %}