chicagodir/directory/views.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
import csv

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required

from chicagodir.directory.models import Directory, Page, get_all_jobs

blueprint = Blueprint("dir", __name__, static_folder="../static")


@blueprint.route("/dir/", methods=["GET", "POST"])
def directory_listing():
    """Show all the directories."""

    return render_template("dir/direct_listing.html", directories=Directory.query.all())


@blueprint.route("/jobs/", methods=["GET", "POST"])
def profession_listing():
    """Show all the known professions."""

    return render_template("dir/job_listing.html", jobs=get_all_jobs())


@blueprint.route("/dir/new", methods=["GET", "POST"])
@login_required
def new_directory():
    """Create a new directory."""
    d = Directory(name="Lakeside Directory", year="1911", tag="lakeside-1911")
    d.save()
    return redirect("/dir/")


@blueprint.route("/dir/<string:tag>/", methods=["GET", "POST"])
def view_directory(tag: str):
    """Show the pages in a directory."""
    d = Directory.query.filter_by(tag=tag).one()
    return render_template("dir/direct_index.html", directory=d)


@blueprint.route("/dir/<string:tag>/p/<int:page>", methods=["GET", "POST"])
def view_page(tag: str, page: int):
    """View a single page of a directory."""
    d = Directory.query.filter_by(tag=tag).one()
    page = Page.query.filter_by(directory_id=d.id, number=page).first()
    return render_template("dir/page_listing.html", directory=d, page=page)


@blueprint.route("/dir/<string:tag>/p/<int:page_id>/fix", methods=["GET", "POST"])
def fix_page(tag: str, page_id: int):
    """Apply standard fixes to a page of a directory."""
    d = Directory.query.filter_by(tag=tag).one()
    page = Page.query.filter_by(directory_id=d.id, number=page_id).first()
    for entry in page.entries:
        if entry.home_address:
            if entry.home_address.find_street():
                entry.save()
    return redirect(url_for("dir.view_page", tag=tag, page=page_id))


@blueprint.route("/dir/<string:tag>/page/upload", methods=["GET", "POST"])
@login_required
def upload_csv(tag: str):
    """Upload a csv file representing a page of a directory."""
    d = Directory.query.filter_by(tag=tag).one()
    if request.method == "POST":
        # check if the post request has the file part
        if "file" not in request.files:
            flash("No file part")
            return redirect(request.url)
        file = request.files["file"]
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == "":
            flash("No selected file")
            return redirect(request.url)
        if file:
            csv_output = d.new_page(
                list(csv.DictReader(x.decode() for x in file.stream))
            )
        else:
            csv_output = []
    return render_template("dir/new_page.html", csv_output=csv_output, directory=d)

chicagodir/templates/dir/direct_index.html
{% extends "layout.html" %}
{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->

<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item"><a href="/dir/">Directories</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{directory.name}} - {{directory.year}}</li>
        </ol>
      </nav>
    <h2>{{directory.name}} - {{directory.year}}</h2>

      <a href="/dir/{{directory.tag}}/streetlist">list of streets</a>
    <h3>Pages</h3>
    {% for page in directory.pages %}
    <div><a href="/dir/{{directory.tag}}/p/{{page.number}}">{{page.number}}</a></div>
    {% endfor %}

    <div class="card">
        <div class="card-body">
        <h4 class="card-title"> upload a new page</h4>
        <form class="form-inline" id="loginForm" method="POST" enctype="multipart/form-data"
            action="{{ url_for('dir.upload_csv', tag=directory.tag) }}" role="login">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <input type=file name=file>
            <input type=submit value=Upload>
        </form>
    </div></div>
</div>
{% endblock %}

chicagodir/templates/dir/direct_listing.html
{% extends "layout.html" %}
{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">

    <h1 class="display-3">Welcome to chicago city directories</h1>

  </div>
</div><!-- /.jumbotron -->

<div class="container">

  <p>Still in Development</p>
  {% for directory in directories %}
  <div><a href="/dir/{{directory.tag}}/">{{directory.name}}</a> {{directory.year}}</div>
  {% endfor %}

  <a href="/dir/new">new directory</a>

</div>
{% endblock %}

chicagodir/templates/dir/job_listing.html
{% extends "layout.html" %}
{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">

        <h1 class="display-3">known professions</h1>

    </div>
</div><!-- /.jumbotron -->

<div class="container">
    {% for job in jobs %}
    <div>{{job}} {{count}}</div>
    {% endfor %}


</div>
{% endblock %}

chicagodir/templates/dir/new_page.html
{% extends "layout.html" %}
{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">

        <h1 class="display-3">Welcome to chicago city directories</h1>

    </div>
</div><!-- /.jumbotron -->

<div class="container">
    <h2>{{directory.name}} - {{directory.year}}</h2>

    <h3>uploaded data:</h3>
    {% for row in csv_output %}
    <div>{{row}}</div>
    {% endfor %}

    <div>
        <h3> upload a new page</h3>
        <form class="form-inline" id="loginForm" method="POST" enctype="multipart/form-data"
            action="{{ url_for('dir.upload_csv', tag=directory.tag) }}" role="login">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <input type=file name=file>
            <input type=submit value=Upload>
        </form>
    </div>
</div>
{% endblock %}

chicagodir/templates/dir/page_listing.html
{% extends "layout.html" %}
{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">

        <h1 class="display-3">{{page.directory.name}} ({{page.directory.year}}), p{{page.number}}</h1>

    </div>
</div><!-- /.jumbotron -->

<div class="container">
    <table>
        <thead>
            <tr>
                <th>Last Name</th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Profession</th>

            </tr>
        </thead>
        {% for entry in page.entries %}
        <tr>
            <td>{{entry.last_name}}</td>
            <td>{{entry.first_name}}</td>
            <td>{{entry.middle_name}}</td>
            <td> {{entry.profession}}</td>
            <td>{{entry.home_address.render()}}
            <td>{% if entry.home_address.street %}
                <a
                    href="
                {{url_for('street.view_street', tag=entry.home_address.street.street_id)}}">{{entry.home_address.street.full_name}}</a>
                {% else %}
                [no street]
                {% endif %}
            </td>
            </td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

chicagodir/templates/dir/street_list.html
{% extends "layout.html" %}


{% macro validated_field(field) -%}
{% if field.errors %}

{{ field(class_="form-control is-invalid") }}
{% for error in field.errors %}
<div class="invalid-feedback">
    {{error}}
</div>
{% endfor %}
{% else %}
{{ field(class_="form-control") }}
{% endif %}

{%- endmacro %}

{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->

<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/dir/">Directories</a></li>
            <li class="breadcrumb-item"><a
                    href="{{url_for('dir.view_directory', tag=directory.tag)}}">{{directory.name}} -
                    {{directory.year}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">street list</li>
        </ol>
    </nav>
    <h2>{{directory.name}} - {{directory.year}}</h2>

    <form method="post">
        {{ street_list_form.csrf_token }}
        <h2>Editing {{directory.street_list.name}}</h2>
        <div class="row">
            <div class="col">
                <h3>Street List Info</h3>
                <table>

                    <tr>
                        <td><label for="name">Name</label></td>
                        <td>
                            {% if street_list_form.name.errors %}

                            {{ street_list_form.name(class_="form-control is-invalid") }}
                            {% for error in street_list_form.name.errors %}
                            <div class="invalid-feedback">
                                {{error}}
                            </div>
                            {% endfor %}
                            {% else %}
                            {{ street_list_form.name(class_="form-control") }}
                            {% endif %}
                        </td>
                    </tr>

                    <tr>
                        <td><label for="date"></label>Date</label></td>

                        <td>
                            {{street_list_form.date(class_="form-control")}}

                        </td>


                    </tr>

                    <tr>
                        <td><label for="url">URL</label>

                        </td>
                        <td class="align-top">
                            {{validated_field(street_list_form.url)}}
                        </td>
                    </tr>

                </table>

                <h3>Streets</h3>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Street</th>

                            <!-- <th>Date of Change</th>
                                <th>Source</th>-->

                            <th>Remove?</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for entry in directory.street_list.sorted_entries() %}
                        <tr>
                            <td>{{entry.street.full_name}} <i>
                                    {{entry.street.grid_info()}} {{entry.street.short_tag()}}</i>

                            <td><a class="btn btn-primary" href="streetlist/remove/{{entry.id}}">remove</a></td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <th>add a new entry</th>
                            </tg>
                        </tr>

                        <tr>
                            <td><input class="autocomplete" id="street_search">
                                <input type="hidden" name="new_entry_street" id="street_search-id">
                            </td>
                            <!----  <td>{{street_list_form.new_successor_street_date}}</td>
                                <td>{{street_list_form.new_successor_street_note}}</td> -->
                        </tr>
                    </tbody>
                </table>




                {% if street_list_form.errors %}
                <ul class="errors">
                    {% for error, value in street_list_form.errors.items() %}
                    <li>{{ error }} {{value}}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <input class="btn btn-primary" type="submit" value="submit">
            </div>

        </div>
    </form>





</div>
{% endblock %}